data:
  name: root
  password: csquan253905
  ip: 127.0.0.1
  port: 3306
  database: block_data_test

#output:
#  db: "root:csquan253905@tcp(127.0.0.1:3306)/block_data_test?charset=utf8mb4"
#  block_worker: 5
#  tx_worker: 1
#  sql_batch: 500
#  retry_times: 5
#  retry_interval: 300

